### ISSUE TITLE
UX: Risk View unclear

### ISSUE THREAD

**Issue by kosmar** [corona-warn-app/cwa-backlog#15]
<img width="180" alt="Bildschirmfoto 2020-06-19 um 08 42 32" src="https://user-images.githubusercontent.com/1532381/85104518-0b2a6900-b209-11ea-8474-e03b67733f7f.png">

- it is unclear to user what the countdown display does convey and what might happen on day 14?
- detail text after tap does not answer this question
- i would love to propose an improvement, but i also don’t know the answer.

please, can you explain?

**Comment by MichaelPFrey** [comment]
> I would suggest: "21% der letzten 14 Tagen aktiv".
Please do *not* do that. Exposing such statistical information can be used for discrimination. Discrimination based on app usage is unlawful, but exposing information is still unwise. People can safely shutdown their phones when they are home alone.

**Comment by kosmar** [comment]
> Please do _not_ do that

well, thats the data displayed now already, afaik – just rewritten to make some sense for users

**Comment by MichaelPFrey** [comment]
> > Please do _not_ do that
> 
> well, thats the data displayed now already, afaik – just rewritten to make some sense for users
I was unclear in my partial quote - my bad.

Currently, the app shows the days active. paulinepauli (whos comment I partially quoted) suggests to show the activity in percent. Showing how many days the app is active is fine by me. Showing of many percent of the last 14 days it was active how ever is dangerous. (Switching the phone of when home alone does not affect the accuracy for the purpose of the app, but lowers the percentage that the tracing was activated)

**Comment by kosmar** [comment]
> Showing how many days the app is active is fine by me.

the number of days is actually an accumulated and rounded number of active minutes. 
at least thats what the source code seems to suggest what it is.

so if you switch the phone of half the day at home, you will have a display of 7 of 14 days, which you may agree is the same as 50%.

**Comment by kosmar** [comment]
display seems to jump back to 1/14 after day 14.

https://twitter.com/wortkomplex/status/1277917451330740226

not helpful in building trust in the app :(

**Comment by MarkusBreuer** [comment]
No offense intended, but I find the discussions about "what this probably means" amusing. When such an app displays a status and people have to speculate about what it might mean, the UX has a – **major** – issue, which needs to be fixed ASAP. 

Even if the speculations are true or the possibility to find an explanation by googling around, with the UX of an important app intended for a wide audience there should **not** be **any** room for speculation.

**Comment by kosmar** [comment]
recent update feels much better to me. 
any user feedback? thanks!
