### ISSUE TITLE
Allow Australian residents in Germany to install app

### ISSUE THREAD

**Issue by zspitzer** [corona-warn-app/cwa-backlog#18]
The existing issue is locked so I'm filing a new one, please allow Australian app store/play store users to install this app.

https://github.com/corona-warn-app/cwa-backlog/issues/9

**Comment by tkowark** [comment]
As written in #9 , you can add additional countries in the cwa-wishlist repository https://github.com/corona-warn-app/cwa-wishlist/issues/new?labels=country&template=03_additional_country.md

**Comment by zspitzer** [comment]
filed https://github.com/corona-warn-app/cwa-wishlist/issues/105
