### ISSUE TITLE
Info über 1 Risikobegegnung wird nicht gelöscht

### ISSUE THREAD

**Issue by wataga** [corona-warn-app/cwa-backlog#29]
Hallo,
habe nun schon seit 17 Tagen die Info über 1 Risiko-kontakt. Das  Risiko bleibt zum Glück gering. 
Meines Wissens solltr die Meldung nach spätestens 15 Tagen  weg sein. 
Dies ist leider kein Einzelfall.

**Comment by daimpi** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/911

A fix [has been merged](https://github.com/corona-warn-app/cwa-app-android/issues/911#issuecomment-671227418) and will be rolled out with version 1.3 🙂.

**Comment by GPclips** [comment]
Hello @wataga,

since this is a duplicate, I will close the issue. Please feel free to comment in the thread @daimpi has shared above: corona-warn-app/cwa-app-android#911

Thanks,
LMM

Corona-Warn-App Open Source Team
