### ISSUE TITLE
Android: Add more translations (e.g. French, Turkish)

### ISSUE THREAD

**Issue by Jeehut** [corona-warn-app/cwa-backlog#3]
## Current Implementation

Currently only German (and English, kind of?) are supported.

## Suggested Enhancement

We should add the most spoken languages for immigrants (e.g. Turkish, Arabic) and also languages for our neighbor countries who should use the app when they come to Germany (e.g. French, Dutch, Polish).

We should probably add support for a Translation Management System like [Lokalise](https://lokalise.com/) or [Transifex](https://de.transifex.com/) (which both are free for open source projects) to make contributions here easier (for example I could ask my wife who's not a developer to provide Turkish translations then). I could set this up myself if you agree.

## Expected Benefits

Immigrants will be able to understand the app in their native language. This is especially important because they might not know as much about the latest news as native speakers, so we should help them within the apps at least.

Also the borders in Germany will not be closed and people are entering Germany and those people should be able to use this app as well because they also come in contact with people in Germany.

---------
Internal Tracking Id: EXPOSUREAPP-2041

**Comment by cmd-Balys** [comment]
I would definitely like to volunteer to translate and organize proofreading for the Lithuanian language. At least to start preparing translations to have them in place when legal stuff is figured out.

Also, if required I could help with legal issues and public awareness regarding the Lithuanian market. I am a co-owner/product manager of a legal startup in Lithuania.

Though @SebastianWolf-SAP one question first. While the app is available in Lithuanian app stores is it fully functioning in Lithuania – would a user be able to report an infection?
The Lithuanian government is only preparing documents for tender to develop a similar app. While there is a quite low number of infections lately it is rapidly increasing. And if this is app is fully functioning, its use in Lithuania would literally save lives.

**Comment by SebastianWolf-SAP** [comment]
Independently of the legal issues (still a very complicated issue, but we are getting some languages through the door at least) I can of course answer your questions regarding the functionality.

A user who got tested in Lithuania wouldn't be able to report their infection as a valid QR code or a teleTAN is required to submit the result. If you are interested in a cooperation and the steps to connect the existing solution to the Lithuanian infrastructure, please let us know your contact details. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello community,

please follow up, using the country label of the wishlist repository and create country selections. This thread will be closed soon.

Thanks,
LMM
Corona Warn-App Open Source Team
