### ISSUE TITLE
UX Impressum contact not clickable

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-backlog#6]
## Describe the issue
It is not possible to click on the contact information to send directly an e-mail or make a phone call.

## Suggested change
For a better user experience link the e-mail and number field.

---
Internal Tracking ID: EXPOSUREAPP-2886

**Comment by Ein-Tim** [comment]
This has been solved:
![image](https://user-images.githubusercontent.com/67682506/98678155-6b5bac00-235e-11eb-88e3-2e2234f1262e.png)

**Comment by dsarkar** [comment]
Dear @mrascher-cosee,

As @Ein-Tim suggests, this issue has been fixed and we will close it now. Thank you all for contributing.


Best wishes,
DS

---
Corona-Warn-App Open Source Team
