### ISSUE TITLE
Occasionally Warning "Region fuer Kontaktmitteilungen geaendert"

### ISSUE THREAD

**Issue by RalfStachel** [corona-warn-app/cwa-backlog#8]
Hi,

even w/o moving physically, I receive occasionally this warning. 
![IMG_6372](https://user-images.githubusercontent.com/67364676/85529074-000e7900-b60d-11ea-99a6-d2fca5b6d41d.jpg)

This warning seems to be unnecessary and it is not clear between which apps I have to decide.

Best regards
Ralf

**Comment by zhedar** [comment]
This bug concerns the exposure notification framework and needs to be fixed by Apple.
See https://github.com/corona-warn-app/cwa-app-ios/issues/731 for a discussion on this matter.

The app keeps on working regardless.

**Comment by GPclips** [comment]
will be closed due to: https://github.com/corona-warn-app/cwa-app-ios/issues/645#issuecomment-644876375
