### ISSUE TITLE
App is not available in your country - Availability in country specific App Stores

### ISSUE THREAD

**Issue by vollmersj** [corona-warn-app/cwa-backlog#9]
I am currently living in Germany but cannot install the app as my Apple ID is registered in the UK apple App Store. It would be great if it could also be registered in this App Store.
![App is not available in your country](https://user-images.githubusercontent.com/12613127/84776585-c6bc8480-afe0-11ea-9adb-763171fb46fe.jpeg)

-----------
Internal Tracking Id: EXPOSUREAPP-2041

**Comment by SebastianWolf-SAP** [comment]
**NOTICE:** To address countries which are not yet in the list and you want to have them released, **please open a new issue for each country you would like to have released** in our [cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist) repository and use the thumbs up options to vote for them. THANKS!

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by tkowark** [comment]
We have just been informed that the Corona-Warn-App is now also available in the following App Stores:

* Estonia
* Iceland
* Finland
* Greece
* Ireland
* Croatia
* Latvia
* Lithuania
* Malta
* Portugal
* Slovakia
* Slovenia
* Spain
* Hungary
* Cyprus
* Norway
* United Kingdom
* Switzerland

As noted above:
> It may still take a few hours to a few days until the app is available for the individual countries

**Comment by tkowark** [comment]
Two more App stores are now enabled:

* Italy
* Sweden
